// ============================================================================
// IMAGE GOVERNOR — TYPOGRAPHY SYSTEM
// ============================================================================
// Font choices are NEVER generated by AI. They are design decisions.
// Each event type maps to a tested font pairing.
// All fonts are Google Fonts for universal availability.
// ============================================================================

export interface FontPairing {
  id: string;
  name: string;
  /** Display/headline font */
  display: {
    family: string;
    weight: number;
    style: 'normal' | 'italic';
    googleUrl: string;
    letterSpacing: string;
    textTransform: 'none' | 'uppercase' | 'lowercase';
  };
  /** Body/detail font */
  body: {
    family: string;
    weight: number;
    style: 'normal' | 'italic';
    googleUrl: string;
    letterSpacing: string;
  };
  /** Size scale in px — responsive scaling applied by renderer */
  scale: {
    heroTitle: number;
    subtitle: number;
    body: number;
    caption: number;
    cta: number;
  };
  /** Best for these categories */
  bestFor: string[];
}

export const FONT_PAIRINGS: Record<string, FontPairing> = {

  EDITORIAL_SHARP: {
    id: 'EDITORIAL_SHARP',
    name: 'Editorial Sharp',
    display: {
      family: 'Playfair Display',
      weight: 800,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@800&display=swap',
      letterSpacing: '-0.02em',
      textTransform: 'none',
    },
    body: {
      family: 'Source Sans 3',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600&display=swap',
      letterSpacing: '0.01em',
    },
    scale: { heroTitle: 64, subtitle: 24, body: 16, caption: 12, cta: 18 },
    bestFor: ['fashion', 'art', 'literary', 'luxury'],
  },

  TECHNICAL_CLEAN: {
    id: 'TECHNICAL_CLEAN',
    name: 'Technical Clean',
    display: {
      family: 'Space Grotesk',
      weight: 700,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@700&display=swap',
      letterSpacing: '-0.03em',
      textTransform: 'none',
    },
    body: {
      family: 'IBM Plex Sans',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&display=swap',
      letterSpacing: '0em',
    },
    scale: { heroTitle: 56, subtitle: 22, body: 16, caption: 12, cta: 16 },
    bestFor: ['tech', 'conference', 'hackathon'],
  },

  BOLD_POSTER: {
    id: 'BOLD_POSTER',
    name: 'Bold Poster',
    display: {
      family: 'Bebas Neue',
      weight: 400, // Bebas only has 400
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
    },
    body: {
      family: 'Barlow',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Barlow:wght@400;600&display=swap',
      letterSpacing: '0.02em',
    },
    scale: { heroTitle: 80, subtitle: 24, body: 16, caption: 12, cta: 20 },
    bestFor: ['music', 'nightlife', 'festival', 'concerts'],
  },

  ORGANIC_WARM: {
    id: 'ORGANIC_WARM',
    name: 'Organic Warm',
    display: {
      family: 'DM Serif Display',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap',
      letterSpacing: '-0.01em',
      textTransform: 'none',
    },
    body: {
      family: 'DM Sans',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&display=swap',
      letterSpacing: '0.01em',
    },
    scale: { heroTitle: 56, subtitle: 22, body: 16, caption: 12, cta: 16 },
    bestFor: ['wellness', 'food', 'retreat', 'ceremony'],
  },

  MARKET_HANDMADE: {
    id: 'MARKET_HANDMADE',
    name: 'Market Handmade',
    display: {
      family: 'Fraunces',
      weight: 700,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Fraunces:wght@700&display=swap',
      letterSpacing: '-0.01em',
      textTransform: 'none',
    },
    body: {
      family: 'Outfit',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500&display=swap',
      letterSpacing: '0em',
    },
    scale: { heroTitle: 52, subtitle: 22, body: 16, caption: 12, cta: 16 },
    bestFor: ['markets', 'makers', 'vintage', 'craft'],
  },

  BRUTALIST_RAW: {
    id: 'BRUTALIST_RAW',
    name: 'Brutalist Raw',
    display: {
      family: 'Anton',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=Anton&display=swap',
      letterSpacing: '0em',
      textTransform: 'uppercase',
    },
    body: {
      family: 'JetBrains Mono',
      weight: 400,
      style: 'normal',
      googleUrl: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400&display=swap',
      letterSpacing: '0em',
    },
    scale: { heroTitle: 72, subtitle: 20, body: 14, caption: 11, cta: 16 },
    bestFor: ['experimental', 'underground', 'punk', 'rave'],
  },
};

// ============================================================================
// CATEGORY → FONT PAIRING MAP
// ============================================================================

export const CATEGORY_FONT_MAP: Record<string, string[]> = {
  'fashion':     ['EDITORIAL_SHARP', 'ORGANIC_WARM'],
  'food':        ['ORGANIC_WARM', 'MARKET_HANDMADE'],
  'art':         ['EDITORIAL_SHARP', 'BRUTALIST_RAW'],
  'wellness':    ['ORGANIC_WARM', 'EDITORIAL_SHARP'],
  'music':       ['BOLD_POSTER', 'BRUTALIST_RAW'],
  'nightlife':   ['BOLD_POSTER', 'BRUTALIST_RAW'],
  'markets':     ['MARKET_HANDMADE', 'ORGANIC_WARM'],
  'tech':        ['TECHNICAL_CLEAN', 'BRUTALIST_RAW'],
  'literary':    ['EDITORIAL_SHARP', 'ORGANIC_WARM'],
  'conference':  ['TECHNICAL_CLEAN', 'EDITORIAL_SHARP'],
  'default':     ['TECHNICAL_CLEAN', 'EDITORIAL_SHARP'],
};

export function getFontsForCategory(category: string): FontPairing[] {
  const key = category.toLowerCase();
  const ids = CATEGORY_FONT_MAP[key] || CATEGORY_FONT_MAP['default'];
  return ids.map(id => FONT_PAIRINGS[id]).filter(Boolean);
}
